name: Sync to Repository2

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at midnight UTC

jobs:
  push-to-repository2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.email "luciancah@gmail.com"
          git config --global user.name "luciancah"

      - name: Push to Repository2
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          git remote add repo2 https://<TOKEN>:x-oauth-basic@github.com/luciancah/til
          git push repo2 HEAD:main -f
